---
- name: Create nginx configuration files for each environments
  hosts: localhost
  vars:
    hostList: "{{ lookup('file', '.tmp/instances.tmp') }}"
    count: "{{ lookup('file', '.tmp/count.tmp') }}"
  tasks:
    - name: "Creating configuration for the environment"
      template:
        src: "../config/nginx.conf.j2"
        dest: ".tmp/{{ item.public_ip }}.conf"
      loop: "{{ hostList }}"
      vars:
        ip: "{{ item.private_ip }}"