---
- hosts: aws
  become: true
  become_user: root
  vars:
    container_count: 1
    app_container_name: webapp
    app_container_image: training/webapp
  tasks:
    - name: Wait 300 seconds for server to boot up
      wait_for_connection:
        delay: 1
        timeout: 300

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Installing requires softwares
      block:
        - name: Install required system packages
          apt:
            pkg:
              - apt-transport-https
              - ca-certificates
              - curl
              - tree
              - software-properties-common
              - python3-pip
              - virtualenv
              - python3-setuptools
              - nginx
            state: latest
            update_cache: true

        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker Repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu focal stable
            state: present

        - name: Update apt and install docker-ce
          apt:
            name: docker-ce
            state: latest
            update_cache: true

        - name: Install Docker Module for Python
          pip:
            name: docker

    - name: Adding 'docker' user
      user:
        name: docker
        comment: docker access only
        group: docker
        createhome: yes
        home: /home/docker

    - name: Adding shared folder for application
      file:
        path: /docker/shared
        state: directory
        recurse: yes
        owner: docker
        group: docker

    - name: Pull app docker image
      docker_image:
        name: "{{ app_container_image }}"
        source: pull

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Copying nginx conf
      copy:
        src: ".tmp/{{ lookup('dig', ansible_host) }}.conf"
        dest: /etc/nginx/sites-enabled/default
      notify:
        - restart nginx
        - start application containers
    
    - name: Configure aws-monitor for shutting down ec2 instance if not in use.
      block:
        - name: Create .aws folder for credentials
          file:
            path: ~/.aws
            state: directory
            recurse: yes

        - name: Copy credential for monitor service
          copy:
            src: ".tmp/credentials"
            dest: ~/.aws

        - name: Copy aws-monitor library to host machine
          copy:
            src: ".tmp/aws_monitor-1.0.0-py3-none-any.whl"
            dest: /tmp
      
        - name: Insatll aws-monitor
          pip:
            name: aws-monitor
            extra_args: "--find-links=/tmp"

        - name: Start aws-monitor service
          shell: "aws-monitor -s 5000 -l monitor.log -t 1.0 &"

  handlers:
    - name: restart nginx
      service: 
        name: nginx
        state: restarted
    
    - name: start application containers
      docker_container:
        name: "{{ app_container_name }}{{ item }}"
        image: "{{ app_container_image }}"
        state: started
        restart_policy: always
        ports:
          - 500{{ item }}:5000
        volumes:
          - /docker/shared:/docker/shared
      with_sequence: count={{ container_count }} 